name: Build boilerplate-project-library

on:
  push:
    branches: [ master ]
  pull_request_target:
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'


    - name: Install Jest
      run: yarn && yarn add jest --dev

    - name: Build
      run: make build
